Repository ezsystems/ez-support-tools, pull requests merged in 2020-11, with the labels that each got.

#69 EZP-32097: Expose EzSystemInfo in Admin UI and SystemInfoDumpCommand
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/view.yaml
  src/bundle/Resources/translations/systeminfo.en.xliff
  src/bundle/Resources/views/themes/admin/system_info/my_ibexa.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
  src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
  src/bundle/SystemInfo/Value/IbexaSystemInfo.php
  src/bundle/Tests/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
  src/bundle/Tests/SystemInfo/Collector/_fixtures/composer.json
  src/lib/Component/Dashboard/EzInfoTwigComponent.php
Labels: Improvement, QA approved

#72 [Travis] Added Behat job
  .travis.yml
  .travis/prepare_ezplatform.sh
  composer.json
Labels: Ready for review

#52 Add X-Powered-By Header to promote use of our software
  DependencyInjection/Compiler/SystemInfoCollectorPass.php
  DependencyInjection/Configuration.php
  DependencyInjection/EzSystemsEzSupportToolsExtension.php
  EventSubscriber/AddXPoweredByHeader.php
  EzSystemsEzSupportToolsBundle.php
  Resources/config/services.yml
  SystemInfo/Collector/EzSystemInfoCollector.php
  SystemInfo/Value/EzSystemInfo.php
  Tests/SystemInfo/Collector/EzSystemInfoCollectorTest.php
  Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
  Tests/SystemInfo/Collector/_fixtures/composer.lock
  composer.json
Labels: Ready for QA
