Repository ezsystems/ez-support-tools, pull requests merged in 2020-12, with the labels that each got.

#75 EZP-32221: Removed dependency on outdated doctrine/inflector
  composer.json
  src/bundle/View/Matcher/SystemInfo/Identifier.php
Labels: Improvement

#78 Added configuration for extraction of translations
  src/bundle/DependencyInjection/EzSystemsEzSupportToolsExtension.php
Labels: Improvement

#79 Added missing translation files
  src/bundle/Resources/translations/dashboard.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/systeminfo.en.xliff
Labels: Bug

#80 EZP-32257: Prepared Product name and release detection for Ibexa DXP 3.3
  composer.json
  src/bundle/DependencyInjection/EzSystemsEzSupportToolsExtension.php
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/view.yaml
  src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php
  src/bundle/SystemInfo/Value/IbexaSystemInfo.php
  src/bundle/Tests/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
Labels: Feature, Improvement, QA approved

#76 EZP-32243: Exposed repository object counts in database tab
  src/bundle/DependencyInjection/EzSystemsEzSupportToolsExtension.php
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/translations/systeminfo.en.xliff
  src/bundle/Resources/views/themes/admin/system_info/database.html.twig
  src/bundle/Resources/views/themes/admin/system_info/repository.html.twig
  src/bundle/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/DoctrineDatabaseSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/EzcHardwareSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/RepositorySystemInfoCollector.php
  src/bundle/SystemInfo/Exception/MetricsNotFoundException.php
  src/bundle/SystemInfo/Value/RepositoryMetrics.php
  src/bundle/SystemInfo/Value/RepositorySystemInfo.php
  src/bundle/Tests/DependencyInjection/EzSystemsEzSupportToolsExtensionTest.php
  src/bundle/Tests/SystemInfo/Collector/DoctrineDatabaseSystemInfoCollectorTest.php
  src/bundle/Tests/SystemInfo/Collector/RepositorySystemInfoCollectorTest.php
  src/lib/Storage/AggregateMetricsProvider.php
  src/lib/Storage/Metrics.php
  src/lib/Storage/Metrics/ContentTypesCountMetrics.php
  src/lib/Storage/Metrics/DraftsCountMetrics.php
  src/lib/Storage/Metrics/PublishedContentObjectsCountMetrics.php
  src/lib/Storage/Metrics/RepositoryConnectionAwareMetrics.php
  src/lib/Storage/Metrics/UsersCountMetrics.php
  src/lib/Storage/Metrics/VersionsCountMetrics.php
  src/lib/Storage/MetricsProvider.php
Labels: Feature, QA approved
