Repository ezsystems/ez-support-tools, pull requests merged in 2021-01, with the labels that each got.

#83 EZP-32259: Replaced "ezplatform" commands namespace with "ibexa"
  src/bundle/Command/SystemInfoDumpCommand.php
Labels: Improvement

#84 EC-333: Based Commerce detection on ezcommerce-transaction package
  src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
Labels: Bug, QA approved

#86 EZP-32307: Fixed check version stability
  src/bundle/Resources/config/services.yaml
  src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
  src/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php
  src/bundle/SystemInfo/Value/IbexaSystemInfo.php
  src/bundle/Tests/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
  src/bundle/Tests/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
  src/lib/Tests/VersionStability/VersionStabilityCheckerTest.php
  src/lib/Value/Stability.php
  src/lib/VersionStability/ComposerVersionStabilityChecker.php
  src/lib/VersionStability/VersionStabilityChecker.php
Labels: Bug, QA approved, Ready for review

#85 EZP-32179: Add footer to platform when user is logged in
  src/bundle/Resources/views/themes/admin/system_info/info.html.twig
Labels: QA approved
